name: Build and Publish

on:
  push:
    # Run the 'publish' job on tags
    tags:
      - 'v*'  # Matches any tag starting with "v", e.g., v1.0.0, v2.3.0
    branches:
      - main
  pull_request:
    branches:
      - main  # Runs on PRs targeting the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path:
            - ./node_modules
            - ./site/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Build project
        run: npm run build --workspace=lib

      - name: Upload build artifacts for library
        uses: actions/upload-artifact@v2
        with:
          name: lib-build-output
          path: ./lib/dist

  build-demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path:
            - ./node_modules
            - ./site/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Download build artifacts for library
        uses: actions/download-artifact@v2
        with:
          name: lib-build-output

      - name: Build demo project
        run: npm run build --workspace=demo

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Only runs on a tag push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts for library
        uses: actions/download-artifact@v2
        with:
          name: lib-build-output

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish --workspace=lib --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}